---
language: en
NEED_PLAYERS: 10
INITIAL_ZOMBIE_COUNT: 2
ROUND_COUNT: 3
INFECTION_MEDICINE_TERM: 1200
PREPARATION_TERM: 600
INGAME_REST_TERM: 600
ROUND_TERM: 2400
GIVE_JUMP_SPELL: true
IS_KILL_TOUCH: false
#이 옵션을 켜면 NEED_PLAYERS < 사용자 수 < NEED_PLAYERS * 2 시 전부 같이 게임을 시작합니다. 이 옵션을 사용하면 최초좀비 수가 안 맞을 수 있으니 조심하세요!
IS_FLUSH: false
...
