---
language: en
NEED_PLAYERS: 10
INITIAL_ZOMBIE_COUNT: 2
ROUND_COUNT: 3
INFECTION_MEDICINE_TERM: 1200
PREPARATION_TERM: 600
INGAME_REST_TERM: 600
ROUND_TERM: 2400
GIVE_JUMP_SPELL: true
IS_KILL_TOUCH: false
#When you turn on this option, when NEED_PLAYERS < user count < NEED_PLAYERS * 2, everyone starts game together. It can make imbalance of rate of zombies and humans.
IS_FLUSH: false
UPDATE_CHECK: true
NU_EFFECT: true
IS_DAMAGE_ENABLED: false
...
